// Thin wrapper around the official SPP CLI (Nethermind stellar-private-payments).
//
// Proofs are generated by the CLI on the agent's machine. Accounts are
// `stellar keys` aliases. The relayer is the alias `gd-relay`: STELLAR_BIN
// points at spp-shim/, which asks the operator's relayer for that signature
// and passes every other `stellar` call to the real CLI.

import { execFile } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

export const RELAY_ALIAS = "gd-relay";

const SHIM = fileURLToPath(
  new URL(process.platform === "win32" ? "../spp-shim/stellar.cmd" : "../spp-shim/stellar", import.meta.url),
);
/** The pool this package was published with. */
export const DEFAULT_DEPLOYMENT = fileURLToPath(new URL("../spp-deployments.json", import.meta.url));

export type SppCliCfg = {
  /** Path to the `spp` binary. */
  bin: string;
  /** Circuit artifacts (policy_tx_2_2_*.r1cs, *.graph.bin, *_proving_key.bin). */
  circuits: string;
  /** SPP deployments.json listing the pool. Defaults to the copy shipped with
   *  this package (Renn's own pool on testnet). */
  deployment?: string;
  /** Operator base URL; its /relay endpoints pay the fees on the fresh address's side. */
  relayUrl: string;
  /** Wallet data (notes, keys) per account. Default: a temp directory per account. */
  dataDir?: (account: string) => string;
};

/** Token amount in 7-decimal units -> the CLI's decimal string ("10", "0.25"). */
export function units(amount: bigint): string {
  const whole = amount / 10_000_000n;
  const frac = (amount % 10_000_000n).toString().padStart(7, "0").replace(/0+$/, "");
  return frac ? `${whole}.${frac}` : `${whole}`;
}

export class SppCli {
  cfg: SppCliCfg;
  /** First pool in the deployment file. */
  pool: string;
  private dirs = new Map<string, string>();

  constructor(cfg: SppCliCfg) {
    this.cfg = { ...cfg, deployment: cfg.deployment ?? DEFAULT_DEPLOYMENT };
    this.pool = JSON.parse(readFileSync(this.cfg.deployment!, "utf8")).pools[0].poolContractId;
  }

  /** Binary and circuits present. */
  static ready(bin: string, circuits: string) {
    return (bin === "spp" || existsSync(bin)) && existsSync(join(circuits, "policy_tx_2_2_B.r1cs"));
  }

  private dataDir(account: string) {
    if (this.cfg.dataDir) return this.cfg.dataDir(account);
    if (!this.dirs.has(account)) this.dirs.set(account, mkdtempSync(join(tmpdir(), `spp-${account}-`)));
    return this.dirs.get(account)!;
  }

  /** Delete the temp wallet directories this instance created (notes and keys). */
  cleanup() {
    for (const d of this.dirs.values()) rmSync(d, { recursive: true, force: true });
    this.dirs.clear();
  }

  /**
   * Run the CLI, retrying transient failures.
   *
   * A retry is only safe while nothing has been signed and sent yet, so the
   * output is checked for a submitted transaction first. The indexer's RPC
   * sync is the step that fails now and then, and it runs before signing.
   */
  async runRetrying(account: string, args: string[], signAs?: string, tries = 3): Promise<string> {
    for (let i = 1; ; i++) {
      try {
        return await this.run(account, args, signAs);
      } catch (e) {
        const msg = String(e);
        const sent = /transaction_submitted|tx_hash/.test(msg);
        if (sent || i >= tries) throw e;
        const last = msg.trim().split(/\r?\n/).pop() ?? msg;
        console.warn(`spp ${args[0]}: ${last.slice(0, 80)} - retry ${i}/${tries - 1}`);
        await new Promise((r) => setTimeout(r, 3000));
      }
    }
  }

  run(account: string, args: string[], signAs?: string): Promise<string> {
    const full = [
      "--deployment", this.cfg.deployment!,
      "--circuits-dir", this.cfg.circuits,
      "--data-dir", this.dataDir(account),
      "--account", account,
      ...(signAs ? ["--sign-as", signAs] : []),
      ...args,
    ];
    return new Promise((ok, fail) => {
      const child = execFile(
        this.cfg.bin,
        full,
        { env: { ...process.env, STELLAR_BIN: SHIM, GD_RELAY_URL: this.cfg.relayUrl }, maxBuffer: 16 << 20, timeout: 300_000 },
        (err, stdout, stderr) => (err ? fail(new Error(`spp ${args[0]}: ${stderr || err.message}`)) : ok(stdout + stderr)),
      );
      // onboard's prompts (bootnode, explorer) take their defaults on empty input
      child.stdin?.end();
    });
  }

  private static txHash(out: string) {
    const m = out.match(/tx_hash\W+([0-9a-f]{64})/);
    if (!m) throw new Error(`no tx_hash in spp output:\n${out.slice(-400)}`);
    return m[1];
  }

  /** Accept the disclaimer and derive the account's privacy keys (local, no transaction). */
  async onboard(account: string) {
    await this.runRetrying(account, ["onboard", "--accept", "--no-register", "--no-bootnode"]);
  }

  /** Deposit public tokens into the pool. The wallet pays its own fee: it is public anyway. */
  async deposit(account: string, amount: bigint) {
    return SppCli.txHash(await this.runRetrying(account, ["deposit", this.pool, units(amount)]));
  }

  /** Withdraw to `to`. Source and fee payer is the relayer, so the wallet does not appear. */
  async withdraw(account: string, amount: bigint, to: string) {
    return SppCli.txHash(await this.runRetrying(account, ["withdraw", this.pool, units(amount), "--to", to], RELAY_ALIAS));
  }
}
